spring:
  application:
    name: compress
  profiles:
    active: test

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.mf.model
server:
  port: 8091
logging:
  level:
    root: info
  file:
    name: logs/server.log
management:
  metrics:
    export:
      prometheus:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
      probes:
        enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
app:
  jwt:
    jwt-id: "compress"
    authorities: "authorities"
    token-expire-time: 1000000

