apiVersion: apps/v1
kind: Deployment
metadata:
  name: compress-ui-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compress-ui
  template:
    metadata:
      labels:
        app: compress-ui
    spec:
      containers:
        - name: compress-ui
          image: pingzhu/compress-ui:1.0.0
          ports:
            - containerPort: 3002