apiVersion: apps/v1
kind: Deployment
metadata:
  name: compress-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compress
  template:
    metadata:
      labels:
        app: compress
    spec:
      containers:
        - name: compress
          image: pingzhu/compress:1.0.7
          ports:
            - containerPort: 8091
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8091
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8091
            initialDelaySeconds: 3
            periodSeconds: 3
